### ISSUE TITLE
Not supported by Kodi 17.

### ISSUE THREAD

**Issue by ned-martin** [aussieaddons/plugin.video.live.au.abc_news24#2]
Updating to Kodi 17 disables this add-on.

**Comment by andybotting** [comment]
It is deprecated and doesn't work any more.

You'll want to try the new iView addon (currently in development) that includes the live channels.

Follow the instructions at http://aussieaddons.com/development/ to set up our development repo and try out the new iView addon, and let me know how that goes.

**Comment by ned-martin** [comment]
Thanks. I have the iView add-on, but as far as I can see, it does not include realtime live ABC News 24? Just archived stuff? Maybe I am missing something?

**Comment by andybotting** [comment]
You need the development version. Currently it is version 1.7.6-22-g5932441.
